FROM ubuntu:24.04

RUN yes | unminimize && apt-get update && apt-get install -y cron && apt-get install -y vim && apt-get install -y gcc && apt-get install -y man && apt-get install -y manpages-posix && apt-get install -y make && apt-get install -y time && apt-get install -y awk
