#!/usr/bin/env bash

run_cmd() {
    if [ "$1" != 'bg' ] && [ "$1" != 'fg' ]; then
	echo "first parameter $1 must be 'fg' or 'bg'"
	exit
    fi
    if [ -n "$2" ]; then
	if [ ! -f "$2" ]; then
	    echo "file: $2"' does not exist!'
	    exit
	fi
	local cmd_dir=$(dirname "$2")
	if [ $(basename "$cmd_dir") == 'saved_configs' ]; then
	    local cmd_dir=$(dirname "$cmd_dir")
	fi
    else
	local cmd_dir=$(pwd)
    fi

    local datetime=$(date '+%Y-%m-%dT%Hh%Mm%Ss')
    local cmd_run_date_dir=$cmd_dir/runs/$(echo $datetime | cut -c -10)
    mkdir -p $cmd_run_date_dir
    mkdir -p $FLANK_ROOT/$(echo $datetime | cut -c -10)
    local cmd_run_dir=$cmd_dir/runs/$(echo $datetime | cut -c -10)/$(echo $datetime | cut -c 12-17)
    if ! mkdir $cmd_run_dir 2> /dev/null; then
	# include seconds
	cmd_run_dir=$cmd_dir/runs/$(echo $datetime | cut -c -10)/$(echo $datetime | cut -c 12-20)
	if ! mkdir $cmd_run_dir 2> /dev/null; then
	    local i=2
	    local flogdir_base=$cmd_run_dir
	    cmd_run_dir=$flogdir_base'_'$i
	    until mkdir $cmd_run_dir 2> /dev/null ; do
		i=$(($i + 1))
		cmd_run_dir=$flogdir_base'_'$i
	    done
	fi
    fi

    if [ -n "$2" ]; then
	if [ $(basename "$2") == 'template.mk' ]; then
	    cp "$2" $cmd_run_dir/exec.mk
	else
	    cp "$2" $cmd_run_dir/exec.sh
	fi
    else
	if [ -f "$cmd_dir/template.mk" ]; then
	    cp $cmd_dir/template.mk $cmd_run_dir/exec.mk
	else
	    cp $cmd_dir/template.sh $cmd_run_dir/exec.sh
	fi
    fi

    local PID=''
    handle_int(){
      if [ -n "$PID" ]; then
	exit_code=$((128 + $(kill -l SIGINT)))
        printf 'ExitCode:\t%d\nEndTime:\t%d' $exit_code $(date '+%s') >> $cmd_run_dir/status
	kill -s SIGINT $PID
	exit $exit_code
      fi
    }
    handle_term(){
      if [ -n "$PID" ]; then
	exit_code=$((128 + $(kill -l SIGTERM)))
        printf 'ExitCode:\t%d\nEndTime:\t%d\n' $exit_code $(date '+%s') >> $cmd_run_dir/status
	kill -s SIGTERM $PID
	exit $exit_code
      fi
    }
    handle_kill(){
      if [ -n "$PID" ]; then
	exit_code=$((128 + $(kill -l SIGKILL)))
        printf 'ExitCode:\t%d\nEndTime:\t%d\n' $exit_code $(date '+%s') >> $cmd_run_dir/status
	kill -s SIGKILL $PID
	exit $exit_code
      fi
    }
    if [ "$1" == 'fg' ]; then
	trap handle_int INT
	trap handle_term TERM
	trap handle_kill KILL
    fi
    # Subtle quoting things:
    #  - $? needs to be escaped as \$? in "" or it will immediately evaluate
    #  - $(date) needs to be single quoted or it will immediately evaluate
    #  - $? needs to be evaluated before $(date) or it will return the exit code of $(date)
    if [ -f "$cmd_run_dir/exec.mk" ]; then
	if [ "$1" == 'bg' ]; then
	    nohup bash -c "printf 'StartTime:\t%s\n' "'$(date "+%s")'" > $cmd_run_dir/status; make -j -f $cmd_run_dir/exec.mk all 1> $cmd_run_dir/stdout.log 2> $cmd_run_dir/stderr.log ; printf 'ExitCode:\t%d\nEndTime:\t%d\n' \$? "'$(date "+%s")'" >> $cmd_run_dir/status" > testtest &
	else
	    printf 'StartTime:\t%s\n' $(date "+%s") > $cmd_run_dir/status
	    make -j -f $cmd_run_dir/exec.mk all 1> $cmd_run_dir/stdout.log 2> $cmd_run_dir/stderr.log & 
	    PID=$!
	    wait $PID
	    printf 'ExitCode:\t%d\nEndTime:\t%d\n' $? "$(date '+%s')" >> $cmd_run_dir/status
	fi
    else
	if [ "$1" == 'bg' ]; then
	    nohup bash -c "printf 'StartTime:\t%s\n' "'$(date "+%s")'" > $cmd_run_dir/status; bash $cmd_run_dir/exec.sh 1> $cmd_run_dir/stdout.log 2> $cmd_run_dir/stderr.log ; printf 'ExitCode:\t%d\nEndTime:\t%d\n' \$? "'$(date "+%s")'" >> $cmd_run_dir/status" > /dev/null &
	else
	    printf 'StartTime:\t%s\n' $(date "+%s") > $cmd_run_dir/status
	    bash $cmd_run_dir/exec.sh 1> $cmd_run_dir/stdout.log 2> $cmd_run_dir/stderr.log & 
	    PID=$!
	    wait $PID
	    local exit_code=$?
	    printf 'ExitCode:\t%d\nEndTime:\t%d\n' $exit_code "$(date '+%s')" >> $cmd_run_dir/status
	    return $exit_code
	fi
    fi
}

if [ -n "$1" ] && [ "$1" == 'run' ]; then 
    if [ -z "$2" ]; then
	echo 'Missing path to template / saved config `iflank run <path>`'
	exit 1
    fi

    exit_code=$(run_cmd "fg" "$2")
    exit $exit_code
fi



PAGE='HOME'
PROMPT='iflank> '
MODE='TTY'

help_msg(){
    printf 'Usage: iflank [run <path>] [--http-mode | -h]\n'
}

while [ "$1" != "" ]; do
    case $1 in
        --http-mode )           
	    MODE='HTTP'
	    PROMPT=''
	    PAGE='HTTP_INIT'
            ;;
        -h | --help ) 
	    help_msg
            exit
	    ;;
        * )              
	    help_msg
            exit 1
    esac
    shift
done

if [ -d /var/lib/flank ]; then
    FLANK_ROOT=/var/lib/flank
elif [ -d /opt/homebrew/var/flank ]; then
    FLANK_ROOT=/opt/homebrew/var/flank
elif [ -d /usr/local/var/flank ]; then
    FLANK_ROOT=/usr/local/var/flank
elif [ -n $(which brew) && $(brew --prefix) > 0 ]; then
    FLANK_ROOT=$(brew --prefix)/var
else 
    echo "Cannot find flank root!"
    exit
fi
PS_VERSION=''

cd $FLANK_ROOT
while true; do
    case "$PAGE" in
	HTTP_INIT)
	    read -rp "$PROMPT" choice
	    case $choice in
		refresh)
		    PAGE='HOME'
		    ;;
		*)
		    echo "Invalid input"
		    ;;
	    esac
	    ;;
	HOME)
	    pwd
	    echo ''
	    if [ $MODE == 'TTY' ]; then
		ls -1
	    else
		ls -1 | awk ' { print "<a onclick=\"run('\''cd "$0"'\'')\">"$0"</a>" } '
	    fi
	    echo ''
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in
		cd)
		    cd $args
		    if [ "$(pwd)" == $FLANK_ROOT/runs ]; then
			PAGE='GLOBAL_RUN_DATES'
		    else
			PAGE='FS'
		    fi
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	GLOBAL_RUN_DATES)
	    pwd
	    echo ''
	    if [ $MODE == 'TTY' ]; then
		find -E $FLANK_ROOT/cmds -type d -regex '.*/[0-9]{4}-[0-9]{2}-[0-9]{2}' \
		    | xargs basename | sort -nr | uniq
	    else
		find -E $FLANK_ROOT/cmds -type d -regex '.*/[0-9]{4}-[0-9]{2}-[0-9]{2}' \
		    | xargs basename | sort -nr | uniq \
		    | awk ' { print $0 } '
	    fi
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in
		setdate)
		    run_date=$args
		    PAGE='GLOBAL_RUN_DATE'
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	GLOBAL_RUN_DATE)
	    echo $(pwd)"?$run_date"
	    echo ''
	    find -E $FLANK_ROOT/cmds -type f -regex '.*/'$run_date'/.*/status' \
		| xargs awk '
		NR==1 { prev=FILENAME; } 
		FNR==1 && NR!=1 { 
		    cmd = "date -r " st " +\"%Y-%m-%d %H:%M:%S\""; 
		    cmd | getline stf; 
		    close(cmd)

		    cmd = "date -r " et " +\"%Y-%m-%d %H:%M:%S\"";
		    cmd | getline etf;
		    close(cmd)

		    print prev, stf, etf;

		    prev=FILENAME; 
		    st=""; 
		    et=""; 
		} 
		/StartTime/ { st=$2; } 
		/EndTime/ { et=$2 } 
		END { 
		    cmd = "date -r " st " +\"%Y-%m-%d %H:%M:%S\""; 
		    cmd | getline stf; 
		    close(cmd)

		    cmd = "date -r " et " +\"%Y-%m-%d %H:%M:%S\"";
		    cmd | getline etf;
		    close(cmd)

		    print prev, stf, etf; 
		}'
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in 
		cd)
		    cd $args
		    PAGE='LOG_DIR'
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	PS)
	    if [ -z $PS_VERSION ]; then
		if [ -n "$(ps --version 2> /dev/null | grep procps)" ]; then 
		    PS_VERSION='procps'
		else
		    PS_VERSION='bsd'
		fi
	    fi
	    if [ $PS_VERSION == 'procps' ]; then 
		ps -eo pid,args | grep "$FLANK_ROOT/.*/exec\." | grep -v "grep .*$FLANK_ROOT" | grep -v "bash -c printf .*StartTime"
	    else
		ps -x | grep "$FLANK_ROOT""/.*/exec\." | grep -v "grep .*""$FLANK_ROOT" | grep -v "bash -c printf .*StartTime"
	    fi
	    echo ''
	    echo '(B)ack / (K)ill <pid> / (L)ogs <pid>'
	    echo ''
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in 
		B)
		    PAGE='HOME'
		    ;;
		K)
		    kill $args 
		    PAGE='PS'
		    ;;
		L)
		    if [ -z $PS_VERSION ]; then
			if [ -n "$(ps --version 2> /dev/null | grep procps)" ]; then 
			    PS_VERSION='procps'
			else
			    PS_VERSION='bsd'
			fi
		    fi
		    if [ $PS_VERSION == 'procps' ]; then 
			log_dir=$(ps e $args | grep -o -e "$FLANK_ROOT""[^[:space:]]*/exec.sh" -e "$FLANK_ROOT""[^[:space:]]*/exec.mk" | xargs dirname)
		    else
			log_dir=$(ps $args | grep -o -e "$FLANK_ROOT""[^[:space:]]*/exec.sh" -e "$FLANK_ROOT""[^[:space:]]*/exec.mk" | xargs dirname)
		    fi
		    cd $log_dir
		    PAGE='LOG_DIR'

		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	FS)
	    pwd
	    echo ""
	    if [ $MODE == 'TTY' ]; then
		ls -1
	    else
		ls -1 | awk ' { print "<a onclick=\"run('\''cd "$0"'\'')\">"$0"</a>" } '
	    fi
	    echo ""
	    echo "Next: cd [dir]"
	    echo ""
	    printf '\0'
	    read -rp "$PROMPT" choice arg
	    case $choice in
		cd)
		    cd $arg
		    if [ -f template.sh ] || [ -f template.mk ]; then
			PAGE='CMD'
		    else
			PAGE='FS'
		    fi
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	CMD)
	    pwd
	    echo ''
	    echo 'Next: (R)un / (L)ogs / (H)ome'
	    echo ''
	    printf '\0'
	    read -rp "$PROMPT" choice
	    case $choice in
		R)
		    run_cmd 'bg'
		    PAGE='CMD'
		    ;;
		L)
		    cd runs
		    PAGE='CMD_RUN_DATES'
		    ;;
		H)
		    cd $FLANK_ROOT
		    PAGE='HOME'
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	CMD_RUN_DATES)
	    pwd
	    echo ''
	    ls -1
	    echo ''
	    echo 'Next: cd [dir]'
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in
		cd)
		    cd $args
		    if [ "$args" == '..' ]; then
			PAGE='CMD'
		    else
			PAGE='LOG_DAY'
		    fi
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	LOG_DAY)
	    pwd
	    echo ''
	    ls -1
	    echo ''
	    echo 'Next: cd [dir]'
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in
		cd)
		    cd $args
		    if [ "$args" == '..' ]; then
			PAGE='CMD'
		    else
			PAGE='LOG_DIR'
		    fi
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	LOG_DIR)
	    pwd
	    echo ''
	    ls -1
	    echo ''
	    echo 'Next: cat [file] / cd [dir]'
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in
		cat)
		    cat $args
		    echo ''
		    ;;
		cd)
		    cd $args
		    if [ "$args" == '..' ]; then
			PAGE='CMD_RUN_DATES'
		    elif [ "$args" == '../..' ]; then
			PAGE='CMD'
		    fi
		    ;;
		refresh)
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	*)
	    echo "Got into weird state. Hit Ctrl-C to quit"
	    ;;
    esac
done
