#!/usr/bin/env bash

PAGE='HOME'
PROMPT='iflank> '
if [ -d /var/lib/flank ]; then
    FLANK_ROOT=/var/lib/flank
elif [ -d /opt/homebrew/var/flank ]; then
    FLANK_ROOT=/opt/homebrew/var/flank
elif [ -d /usr/local/var/flank ]; then
    FLANK_ROOT=/usr/local/var/flank
elif [ -n $(which brew) && $(brew --prefix) > 0 ]; then
    FLANK_ROOT=$(brew --prefix)/var
else 
    echo "Cannot find flank root!"
    exit
fi

cd $FLANK_ROOT
while true; do
    case "$PAGE" in
	HOME)
	    echo 'Welcome to Flank!'
	    echo ''
	    echo '(C)ommands / (P)rocesses'
	    echo ''
	    printf '\0'
	    read -rp "$PROMPT" choice
	    case $choice in
		C)
		    PAGE='FS'
		    ;;
		P)
		    PAGE='PS'
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	PS)
	    ps
	    echo ''
	    echo '(B)ack / (K)ill <pid>'
	    echo ''
	    printf '\0'
	    read -rp "$PROMPT" choice args
	    case $choice in 
		B)
		    PAGE='HOME'
		    ;;
		K)
		    kill $args 
		    PAGE='PS'
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	FS)
	    pwd
	    echo ""
	    ls -1
	    echo ""
	    echo "Next: (G)oto <name>"
	    echo ""
	    printf '\0'
	    read -rp "$PROMPT" choice arg
	    case $choice in
		G)
		    cd $arg
		    if [ -f template.sh ]; then
			PAGE='CMD'
		    else
			PAGE='FS'
		    fi
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	CMD)
	    pwd
	    echo ''
	    echo 'Next: (R)un / (H)ome'
	    echo ''
	    printf '\0'
	    read -rp "$PROMPT" choice
	    case $choice in
		R)
		    RUN_DIR=./runs/$(date -Iseconds)
		    mkdir -p $RUN_DIR
		    nohup bash -c "$(cat template.sh)" 1> $RUN_DIR/stdout.log 2> $RUN_DIR/stderr.log &
		    echo $!
		    PAGE='CMD'
		    ;;
		H)
		    cd $FLANK_ROOT
		    PAGE='HOME'
		    ;;
		*)
		    read -rp "Invalid choice! Hit [Enter] to continue"
		    ;;
	    esac
	    ;;
	*)
	    echo "Got into weird state. Hit Ctrl-C to quit"
	    ;;
    esac
done
