FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y systemd \
    && apt-get install -y curl \
    && apt-get install -y wget \
    && rm -rf /var/lib/apt/lists/*

CMD ["/usr/lib/systemd/systemd"]
